### ISSUE TITLE
review comments

### ISSUE THREAD

**Issue by BUI-studies** [ohiienko-r/js-05-webinar-and-hw#1]
## task-02

прибери префікс `product` з назв властивостей. воно там не потрібно, бо  у назві функції ти уже зазначив шо за обʼєкти створюватимуться. тому не бачу причини уточнювати у кожній властивості до кого/чого вона відноситься.

`verifyStore` все ок. єдиний момент шо замість вкладеного `if` ти можеш використати один з операторів `&&` або `||` та скрафтити одну умову.

**Comment by ohiienko-r** [comment]
0)Прибрав product з назв властивостей.

1)Переписав умову в verifyStore

![image](https://user-images.githubusercontent.com/109099364/235485041-a08a1cfd-a4de-4e31-a37b-071e3829c0c9.png)
